### ISSUE TITLE
Suggestion to use Compact Signature Representation (EIP-2098)

### ISSUE THREAD

**Issue by k06a** [BigWhaleLabs/seal-cred-ledger-contract#27]
If you're using EOA signatures only (not [EIP-1271](https://eips.ethereum.org/EIPS/eip-1271)), I would highly recommend to use compact representation [EIP-2098](https://eips.ethereum.org/EIPS/eip-2098  ). Then signatures size would be 64 bytes in calldata instead of current 160 bytes (32 for array offset + 32 for array length + 65 for RSV + 31 for padding)

**Comment by backmeupplz** [comment]
Should be fixed in https://github.com/BigWhaleLabs/seal-cred-ledger-contract/pull/29, ty
